services:
  root-mcp-server:
    build: .
    container_name: root-mcp-server
    ports:
      - "9090:9090"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=info
      - HOST=0.0.0.0
      - PORT=9090
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://localhost:9090/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ./src:/app/src
    restart: unless-stopped
